import {StyleSheet, Dimensions} from 'react-native';

const {width, height} = Dimensions.get('window');

export const styles = StyleSheet.create({
  container: {
    display: 'flex',
    flexDirection: 'column',
    // flex: 1,
    height,
    backgroundColor: '#FAFCFF',
  },
  headerSection: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-start',
  },
  header: {
    width,
    height: 220,
    backgroundColor: '#6379F4',
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 42,
  },
  headerText: {
    fontSize: 20,
    fontWeight: '700',
    color: 'white',
    marginLeft: 26,
  },
  headerCard: {
    display: 'flex',
    flexDirection: 'row',
    backgroundColor: 'white',
    width: 343,
    height: 96,
    marginTop: 40,
    alignSelf: 'center',
    borderRadius: 10,
  },
  cardImage: {
    height: 56,
    width: 56,
    alignSelf: 'center',
    marginLeft: 16,
  },
  headerCardText: {
    display: 'flex',
    flexDirection: 'column',
    // alignSelf: 'center',
    justifyContent: 'space-evenly',
    marginLeft: 15,
  },
  nameText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#4D4B57',
  },
  phoneNumberText: {
    fontSize: 14,
    fontWeight: '400',
    color: '#7A7886',
  },
  amountContainer: {
    display: 'flex',
    flexDirection: 'row',
    marginTop: 25,
    alignSelf: 'center',
    width,
    justifyContent: 'center',
  },
  textInputStyle: {
    fontWeight: '700',
    fontSize: 42,
    color: '#6379F4',
    alignSelf: 'center',
  },
  balanceText: {
    marginTop: 32,
    fontSize: 16,
    fontWeight: 'bold',
    color: '#7C7895',
    alignSelf: 'center',
  },
  notesStyle: {
    marginTop: 63,
    borderBottomColor: '#6379F4',
    alignSelf: 'flex-end',
  },
  notesText: {
    fontSize: 16,
    color: '#3A3D42',
    fontWeight: '600',
  },
  notesStyleBlur: {
    marginTop: 63,
    borderBottomColor: 'rgba(169, 169, 169, 0.6)',
    alignSelf: 'flex-end',
  },
  submitButton: {
    width: 343,
    height: 57,
    backgroundColor: '#6379F4',
    borderRadius: 12,
    marginTop: 105,
    alignSelf: 'center',
  },
  buttonText: {
    fontSize: 18,
    fontWeight: '600',
  },
  confirmationContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
  },
  cell: {
    width: 162,
    height: 87,
    backgroundColor: 'white',
    elevation: 3,
    borderRadius: 10,
    marginTop: 30,
    padding: 15,
    justifyContent: 'space-between',
  },
  cellTitleText: {
    fontSize: 16,
    fontWeight: '400',
    color: '#7A7886',
  },
  cellChildText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#514F5B',
  },
  longCell: {
    width: 343,
    minHeight: 87,
    backgroundColor: 'white',
    elevation: 3,
    borderRadius: 10,
    marginTop: 30,
    alignSelf: 'center',
    padding: 15,
    justifyContent: 'space-between',
  },
});
